FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN python -m spacy download en_core_web_trf


COPY . .

CMD ["flask", "run", "--host=0.0.0.0", "--reload"]
